# Test $d

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Run
      run: |
        gcc -Ic basics/basics.c; ./a.out
        gcc -Ic bits/bits.c;     ./a.out
        gcc -Ic tree/tree.c;     ./a.out
        gcc -Ic hash/int.c;      ./a.out
