# Test $d

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: 2d
      run: |
        gcc -I. 2d/2d.c -lm;     ./a.out

    - name: Bits
      run: |
        gcc -I. bits/bits.c;     ./a.out

    - name: Hash
      run: |
        gcc -I. hash/int.c;      ./a.out

    - name: Modulo
      run: |
        gcc -I. modulo/modulo.c; ./a.out

    - name: StackLong
      run: |
        gcc -I. stack/long.c;    ./a.out

    - name: Tree
      run: |
        gcc -I. tree/tree.c;     ./a.out
